# Dockerfile
FROM rust:latest AS builder

# Copy the generated Rust project into the Docker container
COPY ./target/release/main /app/main
COPY ./target/release/entity /app/entity
# Add other binaries as necessary

# Expose any necessary ports
EXPOSE 8000

# Set environment variables
ENV HOST=localhost
ENV PORT=8000
ENV DATABASE_URL=postgres://user:password@host:port/database
ENV RUST_LOG=info

# Define the command to run your application
CMD ["/app/main"]
